### ISSUE TITLE
UIOP/UTILITY:PARSE-VERSION: "$VERSION$" doesn't follow asdf version numbering convention

### ISSUE THREAD

**Issue by markhdavid** [fjolliton/cl-vectors#2]
Is use of $VERSION$ in the cl-vector .asd file a bug? a feature? what is that about? any idea?

I think it's the cause of warnings I see like those below.

I think it could be fixed by putting a real version x.y thingee with numbers in there instead. Presumably the version from the file named VERSION, but I don't know.

We are hoping to not have to see all these warnings every compile.

Thank you,

Mark

; Warning: UIOP/UTILITY:PARSE-VERSION: "$VERSION$" doesn't follow asdf version numbering convention
; While executing: (:INTERNAL ASDF/DEFSYSTEM::INVALID-PARSE ASDF/DEFSYSTEM::NORMALIZE-VERSION), in process repl-thread(11).
; Warning: Invalid :version specifier "$VERSION$" for component "cl-vectors" from file #P"lisp/quicklisp/dists/quicklisp/software/cl-vectors-20130312-git/cl-vectors.asd", using NIL instead
; While executing: (:INTERNAL ASDF/DEFSYSTEM::INVALID ASDF/DEFSYSTEM::NORMALIZE-VERSION), in process repl-thread(11).
; Warning: Invalid :version specifier "$VERSION$" for component "cl-vectors" from file #P"lisp/quicklisp/dists/quicklisp/software/cl-vectors-20130312-git/cl-vectors.asd", using NIL instead
; While executing: (:INTERNAL ASDF/DEFSYSTEM::INVALID ASDF/DEFSYSTEM::NORMALIZE-VERSION), in process repl-thread(11).
; Warning: UIOP/UTILITY:PARSE-VERSION: "$VERSION$" doesn't follow asdf version numbering convention
; While executing: (:INTERNAL ASDF/DEFSYSTEM::INVALID-PARSE ASDF/DEFSYSTEM::NORMALIZE-VERSION), in process repl-thread(11).
; Warning: Invalid :version specifier "$VERSION$" for component "cl-aa" from file #P"lisp/quicklisp/dists/quicklisp/software/cl-vectors-20130312-git/cl-aa.asd", using NIL instead
; While executing: (:INTERNAL ASDF/DEFSYSTEM::INVALID ASDF/DEFSYSTEM::NORMALIZE-VERSION), in process repl-thread(11).
; Warning: Invalid :version specifier "$VERSION$" for component "cl-aa" from file #P"lisp/quicklisp/dists/quicklisp/software/cl-vectors-20130312-git/cl-aa.asd", using NIL instead
; While executing: (:INTERNAL ASDF/DEFSYSTEM::INVALID ASDF/DEFSYSTEM::NORMALIZE-VERSION), in process repl-thread(11).
; Warning: UIOP/UTILITY:PARSE-VERSION: "$VERSION$" doesn't follow asdf version numbering convention
; While executing: (:INTERNAL ASDF/DEFSYSTEM::INVALID-PARSE ASDF/DEFSYSTEM::NORMALIZE-VERSION), in process repl-thread(11).
; Warning: Invalid :version specifier "$VERSION$" for component "cl-paths" from file #P"lisp/quicklisp/dists/quicklisp/software/cl-vectors-20130312-git/cl-paths.asd", using NIL instead
; While executing: (:INTERNAL ASDF/DEFSYSTEM::INVALID ASDF/DEFSYSTEM::NORMALIZE-VERSION), in process repl-thread(11).
; Warning: Invalid :version specifier "$VERSION$" for component "cl-paths" from file #P"lisp/quicklisp/dists/quicklisp/software/cl-vectors-20130312-git/cl-paths.asd", using NIL instead

**Comment by fjolliton** [comment]
Thanks. This was merged (some time ago..)
