### ISSUE TITLE
Please tag a version 

### ISSUE THREAD

**Issue by MIvanchev** [fjolliton/cl-vectors#6]
Hey, I'm about to package the library for inclusion in Void Linux so I'd like to ask you to tag a version in Github. I see in the version file the current one is 0.1.5 but it simplifies our process and discussion greatly if there is a Github tagged versin :)

Thanks!

**Comment by fjolliton** [comment]
@MIvanchev I bumped the version to 0.1.6 because of the latest commits, and this is now a tag.

I also fixed some links, and fixed the documentation page while I was at it.

**Comment by MIvanchev** [comment]
Thanks I really really appreciate it!!!
